stages:
  - build
  - deploy

.docker_login: &docker_login
  - mkdir -p /kaniko/.docker
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json

.setup_ssh_token: &setup_ssh_token
  - "which ssh-agent || ( apk update && apk add openssh-client )"
  - mkdir -p ~/.ssh
  - echo -e "$DEV_SSH_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >> ~/.ssh/config

build_front_image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - *docker_login
  cache: {}
  script:
    - echo $CI_COMMIT_TAG > version
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/frontend"
      --dockerfile "${CI_PROJECT_DIR}/frontend/Dockerfile"
      --destination "registry.gitlab.com/ecorium1/rdm/frontend/${CI_COMMIT_REF_SLUG}"

deploy_front_dev:
  stage: deploy
  image: node:18.13.0-alpine3.16
  only:
    - dev
  before_script:
    - *setup_ssh_token
  cache: {}
  dependencies: []
  script:
    - ssh deployer@5.188.130.91 'docker compose pull relfront2 && docker compose up -d relfront2'

deploy_front_prod:
  stage: deploy
  image: node:18.13.0-alpine3.16
  only:
    - main
  before_script:
    - *setup_ssh_token
  cache: {}
  dependencies: []
  script:
    - ssh deployer@109.71.9.125 'docker compose pull relfront2 && docker compose up -d relfront2'

build_api_image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - *docker_login
  cache: {}
  script:
    - echo $CI_COMMIT_TAG > version
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend/api"
      --dockerfile "${CI_PROJECT_DIR}/backend/api/Dockerfile"
      --destination "registry.gitlab.com/ecorium1/rdm/backend/${CI_COMMIT_REF_SLUG}"

deploy_backend_dev:
  stage: deploy
  image: node:18.13.0-alpine3.16
  only:
    - dev
  before_script:
    - *setup_ssh_token
  cache: {}
  dependencies: []
  script:
    - ssh deployer@5.188.130.91 'docker compose pull relapi2 && docker compose up -d relapi2'

deploy_backend_prod:
  stage: deploy
  image: node:18.13.0-alpine3.16
  only:
    - main
  before_script:
    - *setup_ssh_token
  cache: {}
  dependencies: []
  script:
    - ssh deployer@109.71.9.125 'docker compose pull relapi2 && docker compose up -d relapi2'
