export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const CLEAN_CART = 'CLEAN_CART';
export const UPDATE_CART = 'UPDATE_CART';

export const UPDATE_ADDRESS_OF_CART = 'UPDATE_ADDRESS_OF_CARTs';
